
name: Run Java Program

on: [push]

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Compile Java
        run: javac App1/*.java

      - name: Run Java
        run: java App1.Main
