   name: Run Java Program

on: 
  push:
    branches: [ main ]

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile Java
        run: javac App1/src/pack1/Main.java

      - name: Run Java
        run: java -cp App1/src pack1.Main
